version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn package
  post_build:
    commands:
      - echo Build started on `date`
artifacts:
  files:
    - target/CatalogDiscoveryIndexer.jar
    - scripts/*.sh
    - appspec.yml

  discard-paths: yes